03 mongodb
SirotovAlexander/nodejs-homework-repo pull request #2
Opened 2023-09-17 14:42 UTC by SirotovAlexander

Done HW_03

2023-09-18 06:31 UTC, KhYulian commented on controllers/contactControllers.js
> +    if (result === null) {
```suggestion
    if (!contact) {
```

2023-09-18 06:32 UTC, KhYulian commented on controllers/contactControllers.js
> +    const result = await contactsFolder.findById(contactId);
```suggestion
    const contact= await contactsFolder.findById(contactId);
```
давайте зміннім більш контретні назви

2023-09-18 06:32 UTC, KhYulian commented on utils/validation/contactValidationSchemas.js
> +const addSchema = Joi.object({
```suggestion
const addContactValidationSchema = Joi.object({
```

2023-09-18 06:32 UTC, KhYulian requested changes
залишив коменти

2023-09-19 21:59 UTC, SirotovAlexander commented
Переробив згідно із коментарями

2023-09-20 06:19 UTC, merged